<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Fun_PiezaLadoCaballete" Id="{9dba98a8-2d97-436f-a126-f7400ae2c80d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Fun_PiezaLadoCaballete : Uint
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Fun_PiezaLadoCaballete">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>