<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="TFClearAllCmdModulePinza" Id="{a083bc3b-2742-40c4-ad3e-3fa93c56695b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TFClearAllCmdModulePinza : bool
VAR_INPUT
	AspirazioneDX : POINTER TO TF_VacumOVEM;
	AspirazioneSX : POINTER TO TF_VacumOVEM;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TFOVEMClearAllCommand(AspirazioneDX^.Command);
TFOVEMClearAllCommand(AspirazioneSX^.Command);
]]></ST>
    </Implementation>
    <LineIds Name="TFClearAllCmdModulePinza">
      <LineId Id="8" Count="1" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>